version: '3.9'

services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=${APIFORLLMDJANGO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${APIFORLLMDJANGO_POSTGRES_PASSWORD}
      - POSTGRES_DB=${APIFORLLMDJANGO_POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    environment:
      - APIFORLLMDJANGO_SECRET_KEY=${APIFORLLMDJANGO_SECRET_KEY}
      - APIFORLLMDJANGO_DEBUG=${APIFORLLMDJANGO_DEBUG}
      - APIFORLLMDJANGO_ALLOWED_HOSTS=${APIFORLLMDJANGO_ALLOWED_HOSTS}
      - APIFORLLMDJANGO_DEFAULT_FROM_EMAIL=${APIFORLLMDJANGO_DEFAULT_FROM_EMAIL}
      - APIFORLLMDJANGO_EMAIL_BACKEND=${APIFORLLMDJANGO_EMAIL_BACKEND}
      - APIFORLLMDJANGO_EMAIL_HOST=${APIFORLLMDJANGO_EMAIL_HOST}
      - APIFORLLMDJANGO_EMAIL_PORT=${APIFORLLMDJANGO_EMAIL_PORT}
      - APIFORLLMDJANGO_EMAIL_USE_TLS=${APIFORLLMDJANGO_EMAIL_USE_TLS}
      - APIFORLLMDJANGO_EMAIL_HOST_USER=${APIFORLLMDJANGO_EMAIL_HOST_USER}
      - APIFORLLMDJANGO_EMAIL_HOST_PASSWORD=${APIFORLLMDJANGO_EMAIL_HOST_PASSWORD}
      - APIFORLLMDJANGO_TURNSTILE_SECRET_KEY=${APIFORLLMDJANGO_TURNSTILE_SECRET_KEY}
      - APIFORLLMDJANGO_POSTGRES_USER=${APIFORLLMDJANGO_POSTGRES_USER}
      - APIFORLLMDJANGO_POSTGRES_PASSWORD=${APIFORLLMDJANGO_POSTGRES_PASSWORD}
      - APIFORLLMDJANGO_POSTGRES_DB=${APIFORLLMDJANGO_POSTGRES_DB}
      - APIFORLLMDJANGO_ENV=${APIFORLLMDJANGO_ENV}
      - APIFORLLMDJANGO_OPENAI_KEY=${APIFORLLMDJANGO_OPENAI_KEY}
    depends_on:
      - db
      - redis
    restart: always

  celery:
    build: 
      context: .
      dockerfile: docker/celery/Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    environment:
      - APIFORLLMDJANGO_SECRET_KEY=${APIFORLLMDJANGO_SECRET_KEY}
      - APIFORLLMDJANGO_DEBUG=${APIFORLLMDJANGO_DEBUG}
      - APIFORLLMDJANGO_ALLOWED_HOSTS=${APIFORLLMDJANGO_ALLOWED_HOSTS}
      - APIFORLLMDJANGO_DEFAULT_FROM_EMAIL=${APIFORLLMDJANGO_DEFAULT_FROM_EMAIL}
      - APIFORLLMDJANGO_EMAIL_BACKEND=${APIFORLLMDJANGO_EMAIL_BACKEND}
      - APIFORLLMDJANGO_EMAIL_HOST=${APIFORLLMDJANGO_EMAIL_HOST}
      - APIFORLLMDJANGO_EMAIL_PORT=${APIFORLLMDJANGO_EMAIL_PORT}
      - APIFORLLMDJANGO_EMAIL_USE_TLS=${APIFORLLMDJANGO_EMAIL_USE_TLS}
      - APIFORLLMDJANGO_EMAIL_HOST_USER=${APIFORLLMDJANGO_EMAIL_HOST_USER}
      - APIFORLLMDJANGO_EMAIL_HOST_PASSWORD=${APIFORLLMDJANGO_EMAIL_HOST_PASSWORD}
      - APIFORLLMDJANGO_TURNSTILE_SECRET_KEY=${APIFORLLMDJANGO_TURNSTILE_SECRET_KEY}
      - APIFORLLMDJANGO_POSTGRES_USER=${APIFORLLMDJANGO_POSTGRES_USER}
      - APIFORLLMDJANGO_POSTGRES_PASSWORD=${APIFORLLMDJANGO_POSTGRES_PASSWORD}
      - APIFORLLMDJANGO_POSTGRES_DB=${APIFORLLMDJANGO_POSTGRES_DB}
      - APIFORLLMDJANGO_ENV=${APIFORLLMDJANGO_ENV}
      - APIFORLLMDJANGO_OPENAI_KEY=${APIFORLLMDJANGO_OPENAI_KEY}
    depends_on:
      - redis
    restart: always
  
  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./${APIFORLLMDJANGO_NGINX_CONFIG}:/etc/nginx/conf.d/default.conf
      - static_volume:/static:ro
      - /home/sammy/certs:/etc/nginx/certs:ro
    depends_on:
      - web
  
  redis:
    image: redis:7.0
    restart: always

volumes:
  db_data:
  static_volume: