# Generated by Django 4.2.2 on 2023-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=10),
            preserve_default=False,
        ),
    ]
