# Generated by Django 4.2.2 on 2023-07-03 05:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_message_chatmessage_content_chatmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='input_cost',
            field=models.DecimalField(decimal_places=9, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='output_cost',
            field=models.DecimalField(decimal_places=9, default=Decimal('0.0'), max_digits=10),
        ),
    ]
