# Generated by Django 4.2.2 on 2023-07-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chatmessage_input_cost_chatmessage_output_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
