# Generated by Django 4.2.2 on 2023-07-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='_key',
            new_name='key',
        ),
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
