# Generated by Django 4.2.2 on 2023-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_functionserver_chatsession_function_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionserver',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
