# Generated by Django 4.2.2 on 2023-07-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_functionserver_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionschema',
            name='network_access',
            field=models.BooleanField(default=False),
        ),
    ]
