# Generated by Django 4.2.2 on 2023-07-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_functionschema_network_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionschema',
            name='secrets',
            field=models.ManyToManyField(blank=True, to='main.secretkey'),
        ),
    ]
