# Generated by Django 4.2.2 on 2023-07-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_functionschema_secrets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionserver',
            name='api_key',
        ),
    ]
